
INSERT INTO CHUYENDE(MACD,TENCD,HOCPHI,THOILUONG,HINH,MOTA) VALUES(?,?,?,?,?,?)
UPDATE CHUYENDE SET TENCD = ?, HOCPHI = ?, THOILUONG = ?, HINH =?, MOTA = ? WHERE MACD = ?
DELETE CHUYENDE WHERE  MACD = ?
SELECT * FROM CHUYENDE
SELECT * FROM CHUYENDE WHERE MACD = ?

INSERT INTO HOCVIEN(MAHV,MANH,MAKH,DIEM) VALUES(?,?,?,?)
UPDATE HOCVIEN SET DIEM = ? WHERE MAHV = ?
DELETE HOCVIEN WHERE MAHV =?
SELECT*FROM HOCVIEN
SELECT*FROM HOCVIEN WHERE MAHV = ?

INSERT INTO KHOAHOC(MAKH,MACD,HOCPHI,THOILUONG,NGAYKG,GHICHU,NGAYTAO,MANV) VALUES(?,?,?,?,?,?,?,?)
UPDATE KHOAHOC SET HOCPHI = ?, THOILUONG = ?, NGAYKG = ?, GHICHU = ?, NGAYTAO = ? WHERE MAKH = ?
DELETE KHOAHOC WHERE MAKH = ?
SELECT*FROM KHOAHOC
SELECT*FROM KHOAHOC WHERE MAKH = ?

INSERT INTO NGUOIHOC(MANH,HOTEN,GIOITINH,NGAYS,DT,EMAIL,GHICHU,MANV,NGAYDK) VALUES(?,?,?,?,?,?,?,?,?)
UPDATE NGUOIHOC SET HOTEN = ?, GIOITINH = ?, NGAYS = ?, DT = ?, EMAIL = ?, NGAYDK = ?, GHICHU = ? WHERE MANH = ?
DELETE NGUOIHOC WHERE MANH = ?
SELECT*FROM NGUOIHOC WHERE MANH = ?

INSERT INTO NHANVIEN(MANV,MATKHAU,HOTEN,VAITRO) VALUES(?,?,?,?)
UPDATE NHANVIEN SET MATKHAU = ?, HOTEN = ?, VAITRO = ? WHERE MANV = ?
DELETE NHANVIEN WHERE MANV = ?
SELECT*FROM NHANVIEN WHERE MANV = ?