/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package giao_dien;

import entity_edusys.ChuyenDeEntity;
import giao_dien.utils.Auth;
import giao_dien.utils.MsgBox;
import giao_dien.utils.XImage;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author PC
 */
public class CuaSoChinh extends javax.swing.JFrame {

    /**
     * Creates new form CuaSoChinh
     */
    public CuaSoChinh() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
//        setIconImage(XImage.getAppIcon());
//        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
        new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss aa");
                lblTime.setText(sdf.format(new Date()));
            }
        }).start();
        new ChaoJDalog(this, true).setVisible(true);
        new DangNhapDalog(this, true).setVisible(true);
    }

    public void openThongKe(int index) {
        if (Auth.isLogin()) {
            if (index == 3 && !Auth.isManager()) {
                MsgBox.alert(this, "Bạn không có quyền xem doanh thu!");
            } else {
                ThongKe tkwin = new ThongKe(this, true,index);
                tkwin.setVisible(true);
                tkwin.selectTab(index);
            }
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }
    
    public void openHuongDan(){
        try {
            Desktop.getDesktop().browse(new File("help/index.html").toURI());
        } catch (Exception e) {
            System.out.println("Không tìm thấy file hưỡng dẫn!");
            e.printStackTrace();
            throw new RuntimeException(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btDangxuat = new javax.swing.JButton();
        btKetthuc = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btChuyende = new javax.swing.JButton();
        btNguoihoc = new javax.swing.JButton();
        btKhoahoc = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btHuongdan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblQuanlydaotao = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuHethong = new javax.swing.JMenu();
        mniDangnhap = new javax.swing.JMenuItem();
        mniDangxuat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniDoimk = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniKetthuc = new javax.swing.JMenuItem();
        mnuQuanly = new javax.swing.JMenu();
        mniNhanvien = new javax.swing.JMenuItem();
        mniChuyende = new javax.swing.JMenuItem();
        mniNguoihoc = new javax.swing.JMenuItem();
        mniKhoahoc = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        mniHocvien = new javax.swing.JMenuItem();
        mnuThongke = new javax.swing.JMenu();
        mniSonguoihoc = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mniDiemtheokhoa = new javax.swing.JMenuItem();
        mniDiemtheoCD = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mniDoanhthu = new javax.swing.JMenuItem();
        mnuTrogiup = new javax.swing.JMenu();
        mniHuongdan = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mniGioithieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("                                                               HỆ THỐNG QUẢN LÝ ĐÀO TẠO");
        setBackground(new java.awt.Color(255, 102, 0));

        jToolBar1.setRollover(true);

        btDangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Lock.png"))); // NOI18N
        btDangxuat.setText("Đăng xuất");
        btDangxuat.setFocusable(false);
        btDangxuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btDangxuat.setMargin(new java.awt.Insets(2, 20, 2, 20));
        btDangxuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btDangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDangxuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btDangxuat);

        btKetthuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Stop.png"))); // NOI18N
        btKetthuc.setText("Kết thúc");
        btKetthuc.setFocusable(false);
        btKetthuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btKetthuc.setMargin(new java.awt.Insets(2, 20, 2, 20));
        btKetthuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btKetthuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKetthucActionPerformed(evt);
            }
        });
        jToolBar1.add(btKetthuc);
        jToolBar1.add(jSeparator3);

        btChuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Lists.png"))); // NOI18N
        btChuyende.setText("Chuyên đề");
        btChuyende.setFocusable(false);
        btChuyende.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btChuyende.setMargin(new java.awt.Insets(2, 20, 2, 20));
        btChuyende.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btChuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChuyendeActionPerformed(evt);
            }
        });
        jToolBar1.add(btChuyende);

        btNguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Users.png"))); // NOI18N
        btNguoihoc.setText("Người học");
        btNguoihoc.setFocusable(false);
        btNguoihoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNguoihoc.setMargin(new java.awt.Insets(2, 20, 2, 20));
        btNguoihoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNguoihocActionPerformed(evt);
            }
        });
        jToolBar1.add(btNguoihoc);

        btKhoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Address book.png"))); // NOI18N
        btKhoahoc.setText("Khóa học");
        btKhoahoc.setFocusable(false);
        btKhoahoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btKhoahoc.setMargin(new java.awt.Insets(2, 20, 2, 20));
        btKhoahoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btKhoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKhoahocActionPerformed(evt);
            }
        });
        jToolBar1.add(btKhoahoc);
        jToolBar1.add(jSeparator4);

        btHuongdan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Globe.png"))); // NOI18N
        btHuongdan.setText("Hướng dẫn");
        btHuongdan.setFocusable(false);
        btHuongdan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btHuongdan.setMargin(new java.awt.Insets(2, 20, 2, 20));
        btHuongdan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btHuongdan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHuongdanActionPerformed(evt);
            }
        });
        jToolBar1.add(btHuongdan);

        lblQuanlydaotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Info.png"))); // NOI18N
        lblQuanlydaotao.setText("Hệ thống quản lý đào tạo");

        lblTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Alarm.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblQuanlydaotao, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblQuanlydaotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nano.jpg"))); // NOI18N
        jLabel1.setOpaque(true);

        mnuHethong.setText("Hệ thống");

        mniDangnhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangnhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Key.png"))); // NOI18N
        mniDangnhap.setText("Đăng nhập");
        mnuHethong.add(mniDangnhap);

        mniDangxuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Lock.png"))); // NOI18N
        mniDangxuat.setText("Đăng xuất");
        mniDangxuat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mniDangxuatItemStateChanged(evt);
            }
        });
        mniDangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangxuatActionPerformed(evt);
            }
        });
        mnuHethong.add(mniDangxuat);
        mnuHethong.add(jSeparator1);

        mniDoimk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
        mniDoimk.setText("Đổi mật khẩu");
        mniDoimk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoimkActionPerformed(evt);
            }
        });
        mnuHethong.add(mniDoimk);
        mnuHethong.add(jSeparator2);

        mniKetthuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniKetthuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Stop.png"))); // NOI18N
        mniKetthuc.setText("Kết thúc");
        mniKetthuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKetthucActionPerformed(evt);
            }
        });
        mnuHethong.add(mniKetthuc);

        jMenuBar1.add(mnuHethong);

        mnuQuanly.setText("Quản lý");

        mniNhanvien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        mniNhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Clien list.png"))); // NOI18N
        mniNhanvien.setText("Quản lý nhân viên");
        mniNhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNhanvienActionPerformed(evt);
            }
        });
        mnuQuanly.add(mniNhanvien);

        mniChuyende.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        mniChuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Lists.png"))); // NOI18N
        mniChuyende.setText("Quản lý chuyên đề");
        mniChuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniChuyendeActionPerformed(evt);
            }
        });
        mnuQuanly.add(mniChuyende);

        mniNguoihoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        mniNguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Users.png"))); // NOI18N
        mniNguoihoc.setText("Quản lý người học");
        mniNguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNguoihocActionPerformed(evt);
            }
        });
        mnuQuanly.add(mniNguoihoc);

        mniKhoahoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        mniKhoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Address book.png"))); // NOI18N
        mniKhoahoc.setText("Quản lý khóa học");
        mniKhoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKhoahocActionPerformed(evt);
            }
        });
        mnuQuanly.add(mniKhoahoc);
        mnuQuanly.add(jSeparator8);

        mniHocvien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        mniHocvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Flow block.png"))); // NOI18N
        mniHocvien.setText("Quản lý học viên");
        mniHocvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHocvienActionPerformed(evt);
            }
        });
        mnuQuanly.add(mniHocvien);

        jMenuBar1.add(mnuQuanly);

        mnuThongke.setText("Thống kê");

        mniSonguoihoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniSonguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Conference.png"))); // NOI18N
        mniSonguoihoc.setText("Người học theo năm");
        mniSonguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSonguoihocActionPerformed(evt);
            }
        });
        mnuThongke.add(mniSonguoihoc);
        mnuThongke.add(jSeparator5);

        mniDiemtheokhoa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDiemtheokhoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Certificate.png"))); // NOI18N
        mniDiemtheokhoa.setText("Bảng điểm theo khóa học");
        mniDiemtheokhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDiemtheokhoaActionPerformed(evt);
            }
        });
        mnuThongke.add(mniDiemtheokhoa);

        mniDiemtheoCD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDiemtheoCD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Properties.png"))); // NOI18N
        mniDiemtheoCD.setText("Điểm theo chuyên đề");
        mniDiemtheoCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDiemtheoCDActionPerformed(evt);
            }
        });
        mnuThongke.add(mniDiemtheoCD);
        mnuThongke.add(jSeparator6);

        mniDoanhthu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDoanhthu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Dollar.png"))); // NOI18N
        mniDoanhthu.setText("Doanh thu");
        mniDoanhthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoanhthuActionPerformed(evt);
            }
        });
        mnuThongke.add(mniDoanhthu);

        jMenuBar1.add(mnuThongke);

        mnuTrogiup.setText("Trợ giúp");

        mniHuongdan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mniHuongdan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Globe.png"))); // NOI18N
        mniHuongdan.setText("Hướng dẫn sử dụng");
        mniHuongdan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHuongdanActionPerformed(evt);
            }
        });
        mnuTrogiup.add(mniHuongdan);
        mnuTrogiup.add(jSeparator7);

        mniGioithieu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        mniGioithieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Microsoft.png"))); // NOI18N
        mniGioithieu.setText("Giới thiệu sản phẩm");
        mniGioithieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGioithieuActionPerformed(evt);
            }
        });
        mnuTrogiup.add(mniGioithieu);

        jMenuBar1.add(mnuTrogiup);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniDangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangxuatActionPerformed
        // TODO add your handling code here:
        if (MsgBox.confirm(this, "Bạn có chắc muốn đăng xuất?")) {
            Auth.clear();
            new DangNhapDalog(this, true).setVisible(true);
        }
    }//GEN-LAST:event_mniDangxuatActionPerformed

    private void btDangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDangxuatActionPerformed
        // TODO add your handling code here:
        if (MsgBox.confirm(this, "Bạn có chắc muốn đăng xuất?")) {
            Auth.clear();
            new DangNhapDalog(this, true).setVisible(true);
        }
    }//GEN-LAST:event_btDangxuatActionPerformed

    private void mniChuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniChuyendeActionPerformed
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            new QuanLyChuyenDe(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập lại!");
        }
    }//GEN-LAST:event_mniChuyendeActionPerformed

    private void mniNhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNhanvienActionPerformed
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            new QuanLyNhanVien(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập lại!");
        }
    }//GEN-LAST:event_mniNhanvienActionPerformed

    private void mniNguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNguoihocActionPerformed
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            new QuanLyNguoiHoc(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập lại!");
        }
    }//GEN-LAST:event_mniNguoihocActionPerformed

    private void mniKhoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKhoahocActionPerformed
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            new QuanLyKhoaHoc(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập lại!");
        }
    }//GEN-LAST:event_mniKhoahocActionPerformed

    private void mniHocvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHocvienActionPerformed
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            new QuanLyHocVien(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập lại!");
        }
    }//GEN-LAST:event_mniHocvienActionPerformed

    private void btChuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChuyendeActionPerformed
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            new QuanLyChuyenDe(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập lại!");
        }
    }//GEN-LAST:event_btChuyendeActionPerformed

    private void btNguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNguoihocActionPerformed
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            new QuanLyNguoiHoc(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập lại!");
        }
    }//GEN-LAST:event_btNguoihocActionPerformed

    private void btKhoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKhoahocActionPerformed
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            new QuanLyKhoaHoc(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập lại!");
        }
    }//GEN-LAST:event_btKhoahocActionPerformed

    private void mniDoimkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoimkActionPerformed
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            new DoiMatKhau(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập lại!");
        }
    }//GEN-LAST:event_mniDoimkActionPerformed

    private void mniDangxuatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mniDangxuatItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_mniDangxuatItemStateChanged

    private void mniKetthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKetthucActionPerformed
        // TODO add your handling code here:
        if (MsgBox.confirm(this, "Bạn muốn kết thúc làm việc?")) {
            System.exit(0);
        }
    }//GEN-LAST:event_mniKetthucActionPerformed

    private void btKetthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKetthucActionPerformed
        // TODO add your handling code here:
        if (MsgBox.confirm(this, "Bạn muốn kết thúc làm việc?")) {
            System.exit(0);
        }
    }//GEN-LAST:event_btKetthucActionPerformed

    private void mniSonguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSonguoihocActionPerformed
        // TODO add your handling code here:
        openThongKe(1);
    }//GEN-LAST:event_mniSonguoihocActionPerformed

    private void mniDiemtheokhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDiemtheokhoaActionPerformed
        // TODO add your handling code here:
        openThongKe(0);
    }//GEN-LAST:event_mniDiemtheokhoaActionPerformed

    private void mniDiemtheoCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDiemtheoCDActionPerformed
        // TODO add your handling code here:
        openThongKe(2);
    }//GEN-LAST:event_mniDiemtheoCDActionPerformed

    private void mniDoanhthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoanhthuActionPerformed
        // TODO add your handling code here:
        openThongKe(3);
    }//GEN-LAST:event_mniDoanhthuActionPerformed

    private void mniGioithieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGioithieuActionPerformed
        // TODO add your handling code here:
        new GioiThieu(this, true).setVisible(true);
    }//GEN-LAST:event_mniGioithieuActionPerformed

    private void btHuongdanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHuongdanActionPerformed
        // TODO add your handling code here:
        openHuongDan();
    }//GEN-LAST:event_btHuongdanActionPerformed

    private void mniHuongdanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHuongdanActionPerformed
        // TODO add your handling code here:
        openHuongDan();
    }//GEN-LAST:event_mniHuongdanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuaSoChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuaSoChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuaSoChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuaSoChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CuaSoChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btChuyende;
    private javax.swing.JButton btDangxuat;
    private javax.swing.JButton btHuongdan;
    private javax.swing.JButton btKetthuc;
    private javax.swing.JButton btKhoahoc;
    private javax.swing.JButton btNguoihoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblQuanlydaotao;
    private javax.swing.JLabel lblTime;
    private javax.swing.JMenuItem mniChuyende;
    private javax.swing.JMenuItem mniDangnhap;
    private javax.swing.JMenuItem mniDangxuat;
    private javax.swing.JMenuItem mniDiemtheoCD;
    private javax.swing.JMenuItem mniDiemtheokhoa;
    private javax.swing.JMenuItem mniDoanhthu;
    private javax.swing.JMenuItem mniDoimk;
    private javax.swing.JMenuItem mniGioithieu;
    private javax.swing.JMenuItem mniHocvien;
    private javax.swing.JMenuItem mniHuongdan;
    private javax.swing.JMenuItem mniKetthuc;
    private javax.swing.JMenuItem mniKhoahoc;
    private javax.swing.JMenuItem mniNguoihoc;
    private javax.swing.JMenuItem mniNhanvien;
    private javax.swing.JMenuItem mniSonguoihoc;
    private javax.swing.JMenu mnuHethong;
    private javax.swing.JMenu mnuQuanly;
    private javax.swing.JMenu mnuThongke;
    private javax.swing.JMenu mnuTrogiup;
    // End of variables declaration//GEN-END:variables

}
